# Generated by Django 4.2.16 on 2024-11-15 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SawadeeReservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(4)]),
        ),
    ]
